keybindings:
  - key: 13
    action: ':Execute'
  - key: 9
    action: ':Autocomplete'
  - key: 55
    action: ':Exit'
  - key: 127
    action: ':RemoveLeftSymbol'
  - key: 167
    action: ':Close'
  - key: 65517
    action: ':ArrowKeyUp'
  - key: 65516
    action: ':ArrowKeyDown'
  - key: 65515
    action: ':ArrowKeyLeft'
  - key: 65514
    action: ':ArrowKeyRight'

aliases:
  - short: lg
    full: lazygit
prompt: '[{"value": "$SCURDIR", "color":"#f38ba8"},{"value": ">", "color":"#a6e3a1", "bold": true}]'
envs:
  - >-
    $PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/opt/homebrew/bin:/opt/homebrew/sbin:  
  - GOROOT=/Users/senya/go

colors:
  defaultText: "#b4befe"
  defaultBackground: "#1e1e2e"
  selectedForegroundColor : "#f5e0dc"
  windowBorderForegroundColor : "#b3ffb3"
  autocomplete:
    sourceText: "#1e1e2e"
    sourceBackground: "#4db8ff"
    resultKeyText: "#1e1e2e"
    resultBackground: "#eba0ac"
    descriptionText: "#74c7ec"

autocomplete:
  showFileInformation: true
