keybindings:
  - key: 13
    action: ':Execute'
  - key: 14
    action: ':Autocomplete'
  - key: 55
    action: ':Exit'
  - key: 127
    action: ':Backspace'
  - key: 167
    action: ':Close'

aliases:
  - short: lg
    full: lazygit
prompt: 'ASH>'
envs:
  - >-
    $PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/opt/homebrew/bin:/opt/homebrew/sbin:  
  - GOROOT=/Users/senya/go
